courses/urls.py
from django.conf.urls import url
from . import views

app_name = 'courses'
urlpatterns = [
    	url(r'^(?P<pk>\d+)/$',views.CourseDetailView.as_view(), name='detail'),
	url(r'^add/$', views.CourseCreateView.as_view(), name='add'),
	url(r'^edit/(?P<pk>\d+)/$', views.CourseUpdateView.as_view(), name='edit'),
	url(r'^remove/(?P<pk>\d+)/$', views.CourseDeleteView.as_view(), name='remove'),
	url(r'^(?P<pk>\d+)/add_lesson$', views.LessonCreateView.as_view(), name='add-lesson'),

]

polls/urls.py
from django.conf.urls import url
from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

pybursa/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from .views import *



urlpatterns = [
    #url(r'^$', index, name='index'),
    #url(r'^contact/$', contact, name='contact'),
    #url(r'^polls/', include('polls.urls')),
	#url(r'^student_list/$', views.student_list, name='student_list'),
	#url(r'^student_detail/$', views.student_detail, name='student_detail'),
    url(r'^admin/', admin.site.urls),
    url(r'^$', index, name='index'),
    url(r'^courses/', include('courses.urls')),
    url(r'^students/', include('students.urls', namespace="students")),
    url(r'^contact/$', contact, name='contact'),
	url(r'^quadratic/', include('quadratic.urls')),
   	url(r'^coaches/', include('coaches.urls')),
	url(r'^feedback/', include('feedbacks.urls')),
	
	
]

students/urls.py
from django.conf.urls import url

from . import views

app_name = 'students'
urlpatterns = [
    url(r'^$', views.StudentListView.as_view(), name='list_view'),
    url(r'^(?P<pk>\d+)/$', views.StudentDetailView.as_view(), name='detail'),
	url(r'^add/$', views.StudentCreateView.as_view(), name='add'),
	url(r'^edit/(?P<pk>\d+)/$', views.StudentUpdateView.as_view(), name='edit'),
	url(r'^remove/(?P<pk>\d+)/', views.StudentDeleteView.as_view(), name='remove'),
]

students/models.py
from django.db import models
from django.conf import settings
from courses.models import *
from django.core.urlresolvers import reverse

class Student(models.Model):
	name = models.CharField('Имя', max_length=50)   # имя
	surname = models.CharField('Фамилия', max_length=50)  # фамилия
	date_of_birth = models.DateField('Дата рождения')# дата рождения 
	email = models.EmailField('e-mail')
	phone = models.CharField('Телефон', max_length=20)# телефон
	address = models.CharField('Адрес', max_length=200) # адрес
	skype = models.CharField('skype', max_length=20)
	courses = models.ManyToManyField(Course) # курсы, на которых учится студент
	def __str__(self):
            return self.name + " " + self.surname
	def Full_name(self):
	    return " ".join([self.name, self.surname])
	def get_courses(self):
	    return self.courses.all()

# Create your models here.

students/forms.py
#coding: utf-8 
from django import forms
from django.db import models
from students.models import Student


class StudentModelForm(forms.ModelForm):
	class Meta:
		model = Student
		fields = '__all__'

students/views.py
from django.shortcuts import render,redirect
from . models import Student
from courses.models import Course
from django import forms
from . forms import StudentModelForm
from django.contrib import messages
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy


import logging
logger = logging.getLogger(__name__) #pybursa.views

class StudentListView(ListView):
	model = Student
	#template_name = 'students/list.html'
	context_object_name = 'students_list'
	paginate_by = 2

	def get_queryset(self):
		qs = super().get_queryset()
		course_id = self.request.GET.get('course_id')
		if course_id:
			qs = qs.filter(courses_id=course_id)
		return qs

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		return context


#def list_view(request):
#    data = request.GET
#
#    if data:
#        course_id = data['course_id']
#        course = Course.objects.get(id=course_id)
#        students_list = Student.objects.filter(courses__id=course_id)
#
#        context = {
#            'students_list': students_list,
#            'current_course': course,
#        }
#    else:
#        students_list = Student.objects.all()
#        context = {
#            'students_list': students_list
#        }
#
#    return render(request, 'students/list.html', context)


class StudentDetailView(DetailView):
	model = Student

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		logger.debug("Students detail view has been debugged!")
		logger.info("Logger of students detail view informs you!")
		logger.warning("Logger of students detail view warns you!")
		logger.error("Students detail view went wrong!")
		context['title'] = "Student detailed info"
		return context
	#template_name = 'students/detail.html'

#def detail(request, student_id):
#   student = Student.objects.get(id=student_id)
#
#    context = {
#        'student': student
#    }
#
#    return render(request, 'students/detail.html', context)


class StudentCreateView(CreateView):
    model = Student
    form_class = StudentModelForm
    #template_name = 'students/add.html'
    success_url = reverse_lazy('students:list_view')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Student registration'
        return context

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, "Student %s %s has been successfully added." % (self.object.name, self.object.surname))
        return response

#def add(request):
#	if request.method == 'POST':
#		form = StudentModelForm(request.POST)
#		if form.is_valid():
#			student = form.save()
#			message = u"Student %s %s has been successfully added." %(student.name, student.surname)
#			messages.success(request, message)
#			return redirect('students:list_view')
#	else:
#		form = StudentModelForm()
#
#	return render(request, 'students/add.html', {'form':form})


class StudentUpdateView(UpdateView):
    model = Student
    form_class = StudentModelForm
    success_url = reverse_lazy('students:list_view')
    #template_name = 'students/edit.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Student info update'
        return context

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, 'Info on %s %s the student has been successfully changed.'% (self.object.name, self.object.surname))
        return response


#def edit(request,id):
#	student_inst=Student.objects.get(pk=id)
#	if request.method == 'POST':
#		form = StudentModelForm(request.POST, instance=student_inst)
#		if form.is_valid():
#			student= form.save()
#			message = u"Info on %s %s the student has been sucessfully changed." %(student.name, student.surname)
#			messages.success(request, message)
#			return redirect('students:list_view')
#	else:
#		form = StudentModelForm(instance=student_inst)
#
#	return render(request,"students/edit.html",{"form":form})


class StudentDeleteView(DeleteView):
    model = Student
    success_url = reverse_lazy('students:list_view')
    #template_name = 'students/remove.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Student info suppression'
        return context

    def delete(self, request, *args, **kwargs):
        response = super().delete(self, request, *args, **kwargs)
        messages.success(self.request, 'Info on %s %s the student has been sucessfully deleted.'% (self.object.name, self.object.surname))
        return response

#def remove(request,id):
#	student=Student.objects.get(pk=id)
#	if request.method == 'POST':
#		student.delete()
#		message = u"Info on %s %s has been sucessfully deleted." %(student.name, student.surname)
#		messages.success(request, message)
#		return redirect('students:list_view')
#	return render(request,"students/remove.html",{"student":student})

templates/students/add.html
{% extends "base.html" %}


{% block title %}PyBursa - New Student{% endblock title %}


{% block nav_class_student %}active{% endblock nav_class_student %}


{% load static %}


{% block content %} 


  <div class="page-header"><h3 class="text-center">Добавить нового студента</h3></div>
	<div class="container">
		<form method="post">
			{% csrf_token %}          
			{{ form.as_p }}
			<input type="submit" value="Сохранить"/>
<input type="submit" 
            value="Выход" id="btn_crtlesson_cancel"
            onClick="history.go(-1);return true;">
		</form>
    </div>
</div>

{% endblock content %} 

templates/students/detail.html
{% extends "base.html" %}


{% block title %}PyBursa student detail{% endblock title %}


{% block nav_class_student %}active{% endblock nav_class_student %}


{% block content %} 


{% load static %}


    <div class="page-content">
        <div class="container">

            <h1 class="page-header">{{ student.name }} {{ student.surname }}</h1>

            <div class="table-responsive">
                <table class="table table-bordered table-striped">
                    <tr>
                        <th>Date of birth</th>
                        <td>{{ student.date_of_birth }}</td>
                    </tr>
                    <tr>
                        <th>Address</th>
                        <td>{{ student.address }}</td>
                    </tr>
                    <tr>
                        <th>Email</th>
                        <td>{{ student.email }}</td>
                    </tr>
                    <tr>
                        <th>Skype</th>
                        <td>{{ student.skype }}</td>
                    </tr>
                    <tr>
                        <th>Phone</th>
                        <td>{{ student.phone }}</td>
                    </tr>
                    <tr>
                        <th>Courses</th>
                        <td>
                            {% for course in student.get_courses %}
                                <ul>
                                    <li><a href="{% url 'courses:detail' course.id %}">{{ course.name }}</a></li>
                                </ul>
                            {% endfor %}
                        </td>
                    </tr>
                </table>
            </div>

        </div>
    </div>
{% endblock content %} 

</body>
</html>

templates/students/edit.html
{% extends "base.html" %}


{% block title %}PyBursa - Edit Student{% endblock title %}


{% block nav_class_student %}active{% endblock nav_class_student %}


{% load static %}


{% block content %} 


    <div class="page-header">
        <h2>Редактирование данных студента</h2>
    </div>

    <div class="form-group form-group-lg">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
           <input type="submit" value="Сохранить">
        </form>
</div>

{% endblock content %} 

templates/students/list.html
{% extends "base.html" %}


{% block title %}PyBursa - Students{% endblock title %}


{% block nav_class_student %}active{% endblock nav_class_student %}


{% block content %} 


{% load static %}


{% if messages %}
<div class = "alert alert-success" role="alert">
   {% for message in messages %}
      {{ message }}
   {% endfor %}
</div>
{% endif %}

<div class="container">
    <p><a href="/students/add/" class="btn btn-success" role="button">
       <span class="glyphicon glyphicon-plus"></span> 
       Добавить нового студента
</a></p>




    <div class="page-content">
        <div class="container">

            {% if current_course %}
                <h1 class="page-header">Students of "{{ current_course.name }}" course</h1>
            {% else %}
                <h1 class="page-header">Students of PyBursa</h1>
            {% endif %}

            <div class="table-responsive">
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr class="info">
                            <th>#</th>
                            <th>Name</th>
                            <th>Address</th>
                            <th>Skype</th>
                            <th>Courses</th>
                        </tr>
                  

  </thead>

                    <tbody>
                        {% for student in students_list %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td><a href="{% url 'students:detail' student.id %}">{{ student.name }} {{ student.surname }}</a></td>
                                <td>{{ student.address }}</td>
                                <td>{{ student.skype }}</td>
                                <td>
                                    {% for course in student.get_courses %}
                                        <ul>
                                            <li><a href="{% url 'courses:detail' course.id %}">{{ course.name }}</a></li>
                                        </ul>
                                    {% endfor %}
  <td>
            <a href="{% url 'students:edit' student.id %}" class="btn btn-success" type="button">
              <span class="glyphicon glyphicon-pencil"></span>            
                Изменить
            </a>
</td>

  <td>
            <a href="{% url 'students:remove' student.id %}" class="btn btn-success" type="button">
              <span class="glyphicon glyphicon-pencil"></span>            
                Удалить
            </a>
</td>


                       {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock content %} 

templates/students/remove.html
{% extends "base.html" %}


{% block title %}PyBursa - Remove Student{% endblock title %}


{% block nav_class_student %}active{% endblock nav_class_student %}


{% load static %}


{% block content %} 

<p><h3 class="text-center">Студент  {{ student.name }} {{ student.surname }}  будет удален</h3></p>
    <div class="container">
        <form method="post">
          {% csrf_token %}
          {{ form.as_p }} 
            <br />
            <br />
          <input type="submit" value="Удалить"/>
     		<br />
	    	<br />
        </form>
    </div>
    <hr>
{% endblock content %}

templates/students/student_confirm_delete.html
{% extends "base.html" %}


{% block title %}PyBursa - Remove Student{% endblock title %}


{% block nav_class_student %}active{% endblock nav_class_student %}


{% load static %}


{% block content %} 

<p><h3 class="text-center">Студент  {{ student.name }} {{ student.surname }}  будет удален</h3></p>
    <div class="container">
        <form method="post">
          {% csrf_token %}
          {{ form.as_p }} 
          
          <input type="submit" class="btn btn-danger" value="Удалить"/>
    </form>
    </div>
   <div>
<input type="submit" class="btn btn-success"
            value="Выход" id="btn_crtlesson_cancel"
            onClick="history.go(-1);return true;">      
</div>
{% endblock content %}

templates/students/student_detail.html
{% extends "base.html" %}


{% block title %}PyBursa student detail{% endblock title %}


{% block nav_class_student %}active{% endblock nav_class_student %}


{% block content %} 


{% load static %}


    <div class="page-content">
        <div class="container">

            <h1 class="page-header">{{ student.name }} {{ student.surname }}</h1>

            <div class="table-responsive">
                <table class="table table-bordered table-striped">
                    <tr>
                        <th>Date of birth</th>
                        <td>{{ student.date_of_birth }}</td>
                    </tr>
                    <tr>
                        <th>Address</th>
                        <td>{{ student.address }}</td>
                    </tr>
                    <tr>
                        <th>Email</th>
                        <td>{{ student.email }}</td>
                    </tr>
                    <tr>
                        <th>Skype</th>
                        <td>{{ student.skype }}</td>
                    </tr>
                    <tr>
                        <th>Phone</th>
                        <td>{{ student.phone }}</td>
                    </tr>
                    <tr>
                        <th>Courses</th>
                        <td>
                            {% for course in student.get_courses %}
                                <ul>
                                    <li><a href="{% url 'courses:detail' course.id %}">{{ course.name }}</a></li>
                                </ul>
                            {% endfor %}
                        </td>
                    </tr>
                </table>
            </div>

        </div>
    </div>
{% endblock content %} 

</body>
</html>

templates/students/student_form.html
{% extends "base.html" %}


{% block title %}PyBursa - Edit Student{% endblock title %}


{% block nav_class_student %}active{% endblock nav_class_student %}


{% load static %}


{% block content %} 


    <div class="page-header">
        <h2>Редактирование данных студента</h2>
    </div>

    <div class="form-group form-group-lg">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
           <input type="submit" value="Сохранить"> 
</form>
</div>
<div>
<input type="submit" 
            value="Выход" id="btn_crtlesson_cancel"
            onClick="history.go(-1);return true;">      
</div>

{% endblock content %} 

templates/students/student_list.html
{% extends "base.html" %}


{% block title %}PyBursa - Students{% endblock title %}


{% block nav_class_student %}active{% endblock nav_class_student %}


{% block content %} 


{% load static %}


{% if messages %}
<div class = "alert alert-success" role="alert">
   {% for message in messages %}
      {{ message }}
   {% endfor %}
</div>
{% endif %}

<div class="container">
    <p><a href="/students/add/" class="btn btn-success" role="button">
       <span class="glyphicon glyphicon-plus"></span> 
       Добавить нового студента
</a></p>




    <div class="page-content">
        <div class="container">

            {% if current_course %}
                <h1 class="page-header">Students of "{{ current_course.name }}" course</h1>
            {% else %}
                <h1 class="page-header">Students of PyBursa</h1>
            {% endif %}

            <div class="table-responsive">
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr class="info">
                            <th>#</th>
                            <th>Name</th>
                            <th>Address</th>
                            <th>Skype</th>
                            <th>Courses</th>
                        </tr>
                  

  </thead>

                    <tbody>
                        {% for student in students_list %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td><a href="{% url 'students:detail' student.id %}">{{ student.name }} {{ student.surname }}</a></td>
                                <td>{{ student.address }}</td>
                                <td>{{ student.skype }}</td>
                                <td>
                                    {% for course in student.get_courses %}
                                        <ul>
                                            <li><a href="{% url 'courses:detail' course.id %}">{{ course.name }}</a></li>
                                        </ul>
                                    {% endfor %}
  <td>
            <a href="{% url 'students:edit' student.id %}" class="btn btn-success" type="button">
              <span class="glyphicon glyphicon-pencil"></span>            
                Изменить
            </a>
</td>

  <td>
            <a href="{% url 'students:remove' student.id %}" class="btn btn-success" type="button">
              <span class="glyphicon glyphicon-remove"></span>            
                Удалить
            </a>
</td>


                       {% endfor %}
                    </tbody>
                </table>

{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}"><< previous</a></li>
    {% else %}
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}">next >></a></li>
    {% else %}
    {% endif %}
  </ul>
 {% endif %}

            </div>
        </div>
    </div>

{% endblock content %} 