courses/urls.py
from django.conf.urls import url
from . import views

app_name = 'courses'
urlpatterns = [
    	url(r'^(?P<pk>\d+)/$',views.CourseDetailView.as_view(), name='detail'),
	url(r'^add/$', views.CourseCreateView.as_view(), name='add'),
	url(r'^edit/(?P<pk>\d+)/$', views.CourseUpdateView.as_view(), name='edit'),
	url(r'^remove/(?P<pk>\d+)/$', views.CourseDeleteView.as_view(), name='remove'),
	url(r'^(?P<pk>\d+)/add_lesson$', views.LessonCreateView.as_view(), name='add-lesson'),

]

polls/urls.py
from django.conf.urls import url
from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

pybursa/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from .views import *



urlpatterns = [
    #url(r'^$', index, name='index'),
    #url(r'^contact/$', contact, name='contact'),
    #url(r'^polls/', include('polls.urls')),
	#url(r'^student_list/$', views.student_list, name='student_list'),
	#url(r'^student_detail/$', views.student_detail, name='student_detail'),
    url(r'^admin/', admin.site.urls),
    url(r'^$', index, name='index'),
    url(r'^courses/', include('courses.urls')),
    url(r'^students/', include('students.urls', namespace="students")),
    url(r'^contact/$', contact, name='contact'),
	url(r'^quadratic/', include('quadratic.urls')),
   	url(r'^coaches/', include('coaches.urls')),
	url(r'^feedback/', include('feedbacks.urls')),
	
	
]

students/urls.py
from django.conf.urls import url

from . import views

app_name = 'students'
urlpatterns = [
    url(r'^$', views.StudentListView.as_view(), name='list_view'),
    url(r'^(?P<pk>\d+)/$', views.StudentDetailView.as_view(), name='detail'),
	url(r'^add/$', views.StudentCreateView.as_view(), name='add'),
	url(r'^edit/(?P<pk>\d+)/$', views.StudentUpdateView.as_view(), name='edit'),
	url(r'^remove/(?P<pk>\d+)/', views.StudentDeleteView.as_view(), name='remove'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}PyBursa{% endblock title%}</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:400,400i,700,700i" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed menu-opener" data-toggle="collapse" data-target="#main-nav">Menu</button>
                <a class="navbar-brand" href="{% url 'index' %}">PyBursa</a>
            </div>

            <div class="collapse navbar-collapse" id="main-nav">
                <ul class="nav navbar-nav">
                    <li class="{% block nav_class_index %}{% endblock nav_class_index %}"><a href="{% url 'index' %}">Main</a></li>
                    <li class="{% block nav_class_contact %}{% endblock nav_class_contact %}"><a href="{% url 'contact' %}">Contacts</a></li>
                    <li class="{% block nav_class_student %}{% endblock nav_class_student %}"><a href="{% url 'students:list_view' %}">Students</a></li>
		    <li class="{% block nav_class_feedback %}{% endblock nav_class_feedback %}"><a href="{% url 'feedback' %}">Feedback</a></li>
                    
            </div>
        </div>
    </nav>


    <div class="page-content">
        <div class="container">

      
{% block content %}{% endblock content %}


        </div>
    </div>



<div class="panel panel-default text-center">
    <p class="panel-footer"> © 2017 PyBursa ZBondarenko </p>
</div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/contact.html
{% extends "base.html" %}


{% block title %}PyBursa - Contacts{% endblock title %}


{% block nav_class_contact %}active{% endblock nav_class_contact %}


{% block content %} 


{% load static %}

<div class="page-content">
        <div class="container">
            <h1 class="page-header">Contacts</h1>

            
                <div class="persons-list row">
                    <div class="person-item">
                        <div class="thumbnail">
            
                         <img class="person-item__image" src="{% static 'images/IMG_1.JPG' %}" alt="director photo">  

                            <div class="caption">
                                <h3><b>Director</b></h3>
        <p>Name: Ivanov Ivan </p>
        <p>Skype: Ivan21</p>
        <p>Email:Ivanov_Ivan@gmail.com</p>
        <p>Phone:+380991111111</p>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="person-item">
                        <div class="thumbnail">
                            <img class="person-item__image" src="{% static 'images/IMG_2.jpg' %}" alt="manager photo">

                            <div class="caption">
                                <h3><b>Manager</b></h3>
        <p>Name: Mamsimova Mariy</p>
        <p>Skype: Mariy12</p>
        <p>Email: Mamsimova_Mariy@gmail.com</p>
        <p>Phone: +380992222222</p>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="person-item">
                        <div class="thumbnail">
                            <img class="person-item__image" src="{% static 'images/IMG_3.jpg' %}" alt="founder photo">

                            <h3><b>Founder </b></h3>
        <p>Name: Kovalenko Anna</p>
        <p>Skype: Anna13</p>
        <p>Email: Kovalenko_Anna@gmail.com</p>
        <p>Phone: +380993333333</p>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="person-item">
                    

                </div>
            </div>

  {% endblock content %} 

templates/index.html
{% extends "base.html" %}


{% block title %}PyBursa - Main{% endblock title %}


{% block nav_class_index %}active{% endblock nav_class_index %}


{% block content %} 


{% include "include/messages_include.html" %}


{% load static %}
   <div class="jumbotron">
                <h1>PyBursa</h1>
                <p><i>If programming makes you interested, and you know what variables and functions are, then this course is for you.</i></p>
        <h2>Program PyBursa</h2>
        <p>In our course you will be able to master Python. This is a full-fledged language that is used in the development of software</p>
        <h2>Our principles</h2>
        <ol>
          <li>Support</li>
          <li>Focus on practice</li>
          <li>Deadlines</li>
          <li>Refund</li>
        </ol>
        <h2>Your result after the courses</h2>
        <ul type="square">
          <li>a basic level of Python</li>
          <li>a basic level of Django</li>
          <li>instruments Web-developer (html/css, bootstrap, linux, git/github)</li>
        </ul>
            </div>


<div class="container">
    <p><a href="/courses/add/" class="btn btn-success" role="button">
       <span class="glyphicon glyphicon-plus"></span> 
       Добавить новий курс
</a></p>


            <h2 class="page-header">Our courses</h2>

            <div class="table-responsive">
                <table class="table table-bordered courses-table">
                    <thead>
                        <tr class="info">
                            <th class="courses-table__name">Course</th>
                            <th>Description</th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for course in courses_list %}
                            <tr>
                                <th><a href="{% url 'courses:detail' course.id %}">{{ course.name|upper }}</a></th>
                                <td>{{ course.short_description }}</td>
                            </tr>
                        

<td><a href="{% url 'courses:edit' course.id %}" 
	class="btn btn-success" type="button">
              <span class="glyphicon glyphicon-pencil"></span>            
                Изменить
            </a>
</td>

  <td>
            <a href="{% url 'courses:remove' course.id %}" class="btn btn-success" type="button">
              <span class="glyphicon glyphicon-remove"></span>            
                Удалить
            </a>
</td>
{% endfor %}

                    </tbody>
                </table>
            </div>

{% endblock content %}
 