coaches/urls.py
from django.conf.urls import url
from . import views

app_name = 'coaches'

urlpatterns = [
    url(r'(\d)+/$', views.detail, name='detail'),
]

courses/urls.py
from django.conf.urls import url
from . import views

app_name = 'courses'
urlpatterns = [
    	url(r'^(?P<pk>\d+)/$',views.CourseDetailView.as_view(), name='detail'),
	url(r'^add/$', views.CourseCreateView.as_view(), name='add'),
	url(r'^edit/(?P<pk>\d+)/$', views.CourseUpdateView.as_view(), name='edit'),
	url(r'^remove/(?P<pk>\d+)/$', views.CourseDeleteView.as_view(), name='remove'),
	url(r'^(?P<pk>\d+)/add_lesson$', views.LessonCreateView.as_view(), name='add-lesson'),

]

polls/urls.py
from django.conf.urls import url
from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

pybursa/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from .views import *



urlpatterns = [
    #url(r'^$', index, name='index'),
    #url(r'^contact/$', contact, name='contact'),
    #url(r'^polls/', include('polls.urls')),
	#url(r'^student_list/$', views.student_list, name='student_list'),
	#url(r'^student_detail/$', views.student_detail, name='student_detail'),
    url(r'^admin/', admin.site.urls),
    url(r'^$', index, name='index'),
    url(r'^courses/', include('courses.urls')),
    url(r'^students/', include('students.urls', namespace="students")),
    url(r'^contact/$', contact, name='contact'),
	url(r'^quadratic/', include('quadratic.urls')),
   	url(r'^coaches/', include('coaches.urls')),
	url(r'^feedback/', include('feedbacks.urls')),
	
	
]

courses/models.py
from django.db import models
from coaches.models import *

class Course(models.Model):
	name = models.CharField('Название',max_length=200)
	short_description = models.CharField('Кратное описание',max_length=200)
	description = models.TextField('Детальная информация')
	coach = models.ForeignKey(Coach, null = True, blank = True, related_name='coach_courses')
	assistant = models.ForeignKey(Coach, null = True, blank = True, related_name='assistant_courses')
	def __str__(self):
		return self.name

class Lesson(models.Model):
    subject = models.CharField('Тема',max_length=200)
    description = models.TextField('Описание')
    course = models.ForeignKey(Course)
    order = models.PositiveIntegerField()
    def __str__(self):
        return self.subject 

    

# Create your models here.

courses/forms.py
#coding: utf-8 
from django import forms
from django.db import models
from courses.models import Course, Lesson


class CourseModelForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = '__all__'

class LessonModelForm(forms.ModelForm):
    class Meta:
        model = Lesson
        fields = '__all__'

courses/views.py
# encoding: utf-8
from django.shortcuts import redirect
from django.shortcuts import render

from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin

from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from django.core.urlresolvers import reverse_lazy

from courses.models import Course, Lesson
from courses.forms import CourseModelForm, LessonModelForm


import logging
logger = logging.getLogger(__name__)

class CourseDetailView(DetailView):
    model = Course
    context_object_name = 'course'
    template_name = 'courses/detail.html'

    def get_context_data(self, **kwargs):
        context = super(CourseDetailView,self).get_context_data(**kwargs)
        context["lessons"] = Lesson.objects.filter(course_id = self.object)
        context['course'] = Course.objects.get(id=self.object.pk)
        logger.debug("Courses detail view has been debugged")
        logger.info("Logger of courses detail view informs you!")
        logger.warning("Logger of courses detail view warns you!")
        logger.error("Courses detail view went wrong!")
        return context


class CourseCreateView(CreateView):
    model = Course
    context_object_name = 'course'
    template_name = 'courses/add.html'
    success_url = reverse_lazy('index')
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super(CourseCreateView,self).get_context_data(**kwargs)
        context['title'] = 'Course creation'
        return context

    def form_valid(self, form):
        application = form.save()
        msg = u"Course %s has been successfully added." % (application.name)
        messages.success(self.request, msg)
        return super(CourseCreateView, self).form_valid(form)


class CourseUpdateView(UpdateView):
    model = Course
    context_object_name = 'course'
    template_name = 'courses/edit.html'
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super(CourseUpdateView, self).get_context_data(**kwargs)
        context['title'] = u"Course update"
        return context

    def get_success_url(self):
        return reverse_lazy('courses:edit', args=(self.object.id,))

    def form_valid(self, form):
        application = form.save()
        messages.success(
            self.request, u"The changes have been saved.")
        return super(CourseUpdateView, self).form_valid(form)


class CourseDeleteView(DeleteView):
    model = Course
    context_object_name = 'course'
    template_name = 'courses/remove.html'
    success_url = reverse_lazy('index')

    def get_context_data(self, **kwargs):
        context = super(CourseDeleteView, self).get_context_data(**kwargs)
        context['title'] = u"Course deletion"
        context['notice'] = u"The cource %s will be removed" % (
            self.object.name)
        return context

    def delete(self, request, *args, **kwargs):
        messages.success(
            self.request, 'Course {} has been deleted.'.format(self.get_object()))
        return super(CourseDeleteView, self).delete(self, request, *args, **kwargs)


class LessonCreateView(SuccessMessageMixin, CreateView):
    model = Lesson
    context_object_name = 'lessons'
    template_name = 'courses/add_lesson.html'
    success_url = reverse_lazy('courses:detail')
    success_message = "%(subject)s was created successfully"

    def get(self, request, *args, **kwargs):
        course=Course.objects.get(pk=kwargs['pk'])
        form = LessonModelForm(initial = {'course': course.id})
        return render(request, self.template_name , {"form":form})

    def get_success_url(self):
        return reverse_lazy('courses:detail', kwargs={'pk': self.object.course.id})

    def get_context_data(self, **kwargs):
        context = super(LessonCreateView, self).get_context_data(**kwargs)
        context['title'] = u"Lesson creation"
        return context

templates/courses/add.html
{% extends "base.html" %}


{% block title %}PyBursa - Add Courses{% endblock title %}



{% block nav_class_index %}active{% endblock nav_class_index %}


{% block content %} 


{% include "include/messages_include.html" %}


{% load static %}

<div class="page-header"><h3 class="text-center">{{ title }}</h3></div>
	<div class="container">
		<form method="post">
			{% csrf_token %}          
			{{ form.as_p }}
            <input type="submit" value="Сохранить"/>
<input type="submit" 
            value="Выход" id="btn_crtlesson_cancel"
            onClick="history.go(-1);return true;">
		</form>
	</div>
<hr>
{% endblock content %}

templates/courses/add_lesson.html
{% extends "base.html" %}


{% block title %}PyBursa - Add Lesson{% endblock title %}



{% block nav_class_index %}active{% endblock nav_class_index %}


{% block content %} 


{% include "include/messages_include.html" %}


{% load static %}

<div class="page-header">
  <h2 class="text-center">Форма добавления нового занятия</h2>
</div>
<div class="form-group form-group-lg">
		<form method="post">
			{% csrf_token %}          
			{{ form.as_p }}
			<input type="submit" value="Добавить"/>
<input type="submit" 
            value="Выход" id="btn_crtlesson_cancel"
            onClick="history.go(-1);return true;">
		</form>
	</div>
</div>
{% endblock content %}

templates/courses/detail.html
{% extends "base.html" %}


{% block title %}PyBursa - Courses{% endblock title %}



{% block nav_class_index %}active{% endblock nav_class_index %}


{% block content %} 


{% include "include/messages_include.html" %}


{% load static %}


    <div class="page-content">
        <div class="container">

            <div class="jumbotron">
                <h1>{{ course.name }}</h1>
                <p>{{ course.description|truncatechars:32 }}
            </div>

            <h2 class="page-header">Course plan</h2>


<p><a href="{% url 'courses:add-lesson' course.id %}" class="btn btn-success" role="button">
<span class="glyphicon glyphicon-plus"></span>Добавить занятие</a></p>





            <div class="table-responsive">
                <table class="table table-bordered courses-table">
                    <thead>
                        <tr class="info">
                            <th>#</th>
                            <th class="courses-table__name">Subject</th>
                            <th>Description</th>
                        </tr>
                    </thead>

                     <tbody>

        {% for l in lessons %}
          <tr>
            <td>{{ l.order }}</td>
            <td style="width:17%">{{ l.subject }}</td>
            <td style="width:50%">{{ l.description }}</td>
          </tr>
        {% endfor %}
</tbody>
                </table>
            </div>



    <div class="jumbotron">
        <h2>Преподаватели</h2>
    <div><h4>Учитель</h4>

     <a href="{% url 'coaches:detail' course.coach.id %}">{{ course.coach.first_name }} {{ course.coach.last_name }}</a>
    </div>
    <p>{{ course.coach.description }}</p>

   <div><h4>Ассистент</h4>

    <a href="{% url 'coaches:detail' course.assistant.id %}">{{ course.assistant.first_name }} {{ course.assistant.last_name }}</a>
    </div>
    <p>{{ course.assistant.description }}</p>


</div>



        </div>
    </div>
{% endblock content %} 

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/courses/edit.html
{% extends "base.html" %}


{% block title %}PyBursa - Edit Courses{% endblock title %}



{% block nav_class_index %}active{% endblock nav_class_index %}


{% block content %} 


{% include "include/messages_include.html" %}


{% load static %}
 <div class="page-header">
    <h2 class="text-center">{{ title }}</h2>
  </div>

  <div class="form-group form-group-lg">
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Изменить"/>
    </form>
  </div>
  </br>
{% endblock content %}

templates/courses/remove.html
{% extends "base.html" %}


{% block title %}PyBursa - Remove Courses{% endblock title %}



{% block nav_class_index %}active{% endblock nav_class_index %}


{% block content %} 


{% include "include/messages_include.html" %}


{% load static %}
<div class="page-header">
		<h2 class="text-center">Курс {{ course.name }} будет удален</h3>
	</div>
	<div class="form-group form-group-lg">
		<form method="post">
			{% csrf_token %}
			<button type="submit" class="btn btn-danger">Удалить</button>
		</form>
	</div>
	
{% endblock content %}